apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ui
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: services/argocd
    repoURL: https://github.com/tkjftkjf/tkjf-infra
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      enabled: true
