apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wg-easy
  namespace: argocd
spec:
  destination:
    namespace: wg-easy
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: wg-easy
      repoURL: https://raw.githubusercontent.com/hansehe/wg-easy-helm/master/helm/charts/
      targetRevision: 0.1.5
      helm:
        releaseName: wg-easy
        valueFiles:
          - $value/services/wg-easy/values.yaml
        parameters:
          - name: startupapicheck.timeout
            value: "5m"
            forceString: true
          - name: installCRDs
            value: "true"
    - repoURL: https://github.com/tkjftkjf/tkjf-infra
      path: services/wg-easy
      targetRevision: HEAD
      ref: value
      directory:
        recurse: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: true