apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: wireguard
  namespace: argocd

spec:
  destination:
    namespace: wireguard
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: wireguard
      repoURL: https://bryopsida.github.io/wireguard-chart
      targetRevision: 0.31.0
      helm:
        releaseName: wireguard
        valueFiles:
          - $value/services/wireguard/values.yaml
        parameters:
          - name: startupapicheck.timeout
            value: "5m"
            forceString: true
          - name: installCRDs
            value: "true"
    - repoURL: https://github.com/tkjftkjf/tkjf-infra
      path: services/wireguard
      targetRevision: HEAD
      ref: value
      directory:
        recurse: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
